# .gitlab-ci.yml

include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  AUTO_DEVOPS_PLATFORM_TARGET: EC2

build_artifact:
  stage: build
  image: node:12.13-alpine
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - dist/
