version: '3'

services:
  app:
    # expose:
    #   - 3000
    volumes:
      - .:/app
      - /app/node_modules
    # working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: docker
    ports:
      - 5001:5001
    command: npm run start:container

volumes:
  meu-spa-db:
networks:
  meu-spa:
    driver: bridge
